local augend=require("dial.augend")
require("dial.config").augends:register_group{
 -- default augends used when no group name is specified
 default={
  augend.integer.alias.decimal_int,
  augend.integer.alias.hex,
  augend.integer.alias.octal,
  augend.integer.alias.binary,
  augend.integer.alias.decimal,
  augend.date.alias["%Y/%m/%d"],
  augend.date.alias["%m/%d/%Y"],
  augend.date.alias["%d/%m/%Y"],
  augend.date.alias["%m/%d/%y"],
  augend.date.alias["%d/%m/%y"],
  augend.date.alias["%m/%d"],
  augend.date.alias["%-m/%-d"],
  augend.date.alias["%Y-%m-%d"],
  augend.date.alias["%Y年%-m月%-d日"],
  augend.date.alias["%Y年%-m月%-d日(%ja)"],
  augend.date.alias["%H:%M:%S"],
  augend.date.alias["%H:%M"],
  augend.constant.alias.ja_weekday,
  augend.constant.alias.ja_weekday_full,
  augend.constant.alias.bool,
  augend.constant.alias.alpha,
  augend.constant.alias.Alpha,
  -- augend.semver.alias.semver,
  -- augend.paren.alias.quote,
  -- augend.paren.alias.brackets,
  -- augend.paren.alias.lua_str_literal,
  -- augend.paren.alias.rust_str_literal,
  augend.misc.alias.markdown_header,
 },
}
