---@meta Neovim API
---          Mode  | Norm | Ins | Cmd | Vis | Sel | Opr | Term | Lang |
--- Command        +------+-----+-----+-----+-----+-----+------+------+
--- [nore]map      | yes  |  -  |  -  | yes | yes | yes |  -   |  -   |
--- n[nore]map     | yes  |  -  |  -  |  -  |  -  |  -  |  -   |  -   |
--- [nore]map!     |  -   | yes | yes |  -  |  -  |  -  |  -   |  -   |
--- i[nore]map     |  -   | yes |  -  |  -  |  -  |  -  |  -   |  -   |
--- c[nore]map     |  -   |  -  | yes |  -  |  -  |  -  |  -   |  -   |
--- v[nore]map     |  -   |  -  |  -  | yes | yes |  -  |  -   |  -   |
--- x[nore]map     |  -   |  -  |  -  | yes |  -  |  -  |  -   |  -   |
--- s[nore]map     |  -   |  -  |  -  |  -  | yes |  -  |  -   |  -   |
--- o[nore]map     |  -   |  -  |  -  |  -  |  -  | yes |  -   |  -   |
--- t[nore]map     |  -   |  -  |  -  |  -  |  -  |  -  | yes  |  -   |
--- l[nore]map     |  -   | yes | yes |  -  |  -  |  -  |  -   | yes  |
---@alias vim.api.keyset.set_keymap.mode
---| ""
---| "n"
---| "!"
---| "i"
---| "c"
---| "v"
---| "x"
---| "s"
---| "o"
---| "t"
---| "l"
