if vim.env.UNITTEST then
 _G.UnitTest=require("hc-nvim.util.unit_test").new()
 vim.schedule(function()
  UnitTest:test()
 end)
end
---@class hc_nvim.util
local Util=require("hc-nvim.util.init_space")
require("hc-nvim.util.main")
Util.lazy(function() return require("hc-nvim.util.buffercache") end,        function(t) Util.BufferCache=t end)
Util.lazy(function() return require("hc-nvim.util.cache") end,              function(t) Util.Cache=t end)
Util.lazy(function() return require("hc-nvim.util.color") end,              function(t) Util.Color=t end)
Util.lazy(function() return require("hc-nvim.util.conducted_autocmd") end,  function(t) Util.ConductedAutocmd=t end)
Util.lazy(function() return require("hc-nvim.util.conducted_highlight") end,function(t) Util.ConductedHighlight=t end)
Util.lazy(function() return require("hc-nvim.util.conducted_timer") end,    function(t) Util.ConductedTimer=t end)
Util.lazy(function() return require("hc-nvim.util.event") end,              function(t) Util.Event=t end)
Util.lazy(function() return require("hc-nvim.util.fallback") end,           function(t) Util.Fallback=t end)
Util.lazy(function() return require("hc-nvim.util.i18n") end,               function(t) Util.I18n=t end)
Util.lazy(function() return require("hc-nvim.util.interface") end,          function(t) Util.Interface=t end)
Util.lazy(function() return require("hc-nvim.util.key_recorder") end,       function(t) Util.KeyRecorder=t end)
Util.lazy(function() return require("hc-nvim.util.keymod") end,             function(t) Util.Keymod=t end)
Util.lazy(function() return require("hc-nvim.util.lazy") end,               function(t) Util.Lazy=t end)
Util.lazy(function() return require("hc-nvim.util.lazy_tab") end,           function(t) Util.LazyTab=t end)
Util.lazy(function() return require("hc-nvim.util.local_env") end,          function(t) Util.LocalEnv=t end)
Util.lazy(function() return require("hc-nvim.util.mod_tree") end,           function(t) Util.ModTree=t end)
Util.lazy(function() return require("hc-nvim.util.option") end,             function(t) Util.Option=t end)
Util.lazy(function() return require("hc-nvim.util.range_mark") end,         function(t) Util.RangeMark=t end)
Util.lazy(function() return require("hc-nvim.util.reference") end,          function(t) Util.Reference=t end)
Util.lazy(function() return require("hc-nvim.util.register") end,           function(t) Util.Register=t end)
Util.lazy(function() return require("hc-nvim.util.sheet") end,              function(t) Util.Sheet=t end)
Util.lazy(function() return require("hc-nvim.util.task_sequence") end,      function(t) Util.TaskSequence=t end)
Util.lazy(function() return require("hc-nvim.util.ts_proxy") end,           function(t) Util.TSProxy=t end)
Util.lazy(function() return require("hc-nvim.util.type") end,               function(t) Util.Type=t end)
Util.lazy(function() return require("hc-nvim.util.wrapper") end,            function(t) Util.Wrapper=t end)
return Util
