if vim.env.UNITTEST then
 _G.UnitTest=require("hc-nvim.util.unit_test").new()
 vim.schedule(function()
  UnitTest:test()
 end)
end
---@class hc_nvim.util
local Util=require("hc-nvim.util.init_space")
require("hc-nvim.util.main")
Util.Cache             =require("hc-nvim.util.cache")
Util.Color             =require("hc-nvim.util.color")
Util.ConductedAutocmd  =require("hc-nvim.util.conducted_autocmd")
Util.ConductedHighlight=require("hc-nvim.util.conducted_highlight")
Util.ConductedTimer    =require("hc-nvim.util.conducted_timer")
Util.Event             =require("hc-nvim.util.event")
Util.Fallback          =require("hc-nvim.util.fallback")
Util.I18n              =require("hc-nvim.util.i18n")
Util.Interface         =require("hc-nvim.util.interface")
Util.KeyRecorder       =require("hc-nvim.util.key_recorder")
Util.Keymod            =require("hc-nvim.util.keymod")
Util.Lazy              =require("hc-nvim.util.lazy")
Util.LazyTab           =require("hc-nvim.util.lazy_tab")
Util.LocalEnv          =require("hc-nvim.util.local_env")
Util.ModTree           =require("hc-nvim.util.mod_tree")
Util.Option            =require("hc-nvim.util.option")
Util.RangeMark         =require("hc-nvim.util.range_mark")
Util.Reference         =require("hc-nvim.util.reference")
Util.Register          =require("hc-nvim.util.register")
Util.TaskSequence      =require("hc-nvim.util.task_sequence")
Util.Type              =require("hc-nvim.util.type")
Util.Wrapper           =require("hc-nvim.util.wrapper")
return Util
