local builtin=require("telescope.builtin")
local Wrapper=require("hc-nvim.util.wrapper")
return {
 {name=NS.telescope_builtin_autocommands,                 rhs=builtin.autocommands},
 {name=NS.telescope_builtin_buffers,                      rhs=builtin.buffers},
 {name=NS.telescope_builtin_builtin,                      rhs=builtin.builtin},
 {name=NS.telescope_builtin_colorscheme,                  rhs=builtin.colorscheme},
 {name=NS.telescope_builtin_command_history,              rhs=builtin.command_history},
 {name=NS.telescope_builtin_commands,                     rhs=builtin.commands},
 {name=NS.telescope_builtin_current_buffer_fuzzy_find,    rhs=builtin.current_buffer_fuzzy_find},
 {name=NS.telescope_builtin_current_buffer_tags,          rhs=builtin.current_buffer_tags},
 {name=NS.telescope_builtin_diagnostics,                  rhs=builtin.diagnostics},
 {name=NS.telescope_builtin_filetypes,                    rhs=builtin.filetypes},
 {name=NS.telescope_builtin_find_files,                   rhs=builtin.find_files},
 {name=NS.telescope_builtin_git_bcommits,                 rhs=builtin.git_bcommits},
 {name=NS.telescope_builtin_git_bcommits_range,           rhs=builtin.git_bcommits_range},
 {name=NS.telescope_builtin_git_branches,                 rhs=builtin.git_branches},
 {name=NS.telescope_builtin_git_commits,                  rhs=builtin.git_commits},
 {name=NS.telescope_builtin_git_files,                    rhs=builtin.git_files},
 {name=NS.telescope_builtin_git_stash,                    rhs=builtin.git_stash},
 {name=NS.telescope_builtin_git_status,                   rhs=builtin.git_status},
 {name=NS.telescope_builtin_grep_string,                  rhs=builtin.grep_string},
 {name=NS.telescope_builtin_help_tags,                    rhs=builtin.help_tags},
 {name=NS.telescope_builtin_highlights,                   rhs=builtin.highlights},
 {name=NS.telescope_builtin_jumplist,                     rhs=builtin.jumplist},
 {name=NS.telescope_builtin_keymaps,                      rhs=builtin.keymaps},
 {name=NS.telescope_builtin_live_grep,                    rhs=builtin.live_grep},
 {name=NS.telescope_builtin_loclist,                      rhs=builtin.loclist},
 {name=NS.telescope_builtin_lsp_definitions,              rhs=builtin.lsp_definitions},
 {name=NS.telescope_builtin_lsp_implementations,          rhs=builtin.lsp_implementations},
 {name=NS.telescope_builtin_lsp_type_definitions,         rhs=builtin.lsp_type_definitions},
 {name=NS.telescope_builtin_lsp_references,               rhs=builtin.lsp_references},
 {name=NS.telescope_builtin_lsp_incoming_calls,           rhs=builtin.lsp_incoming_calls},
 {name=NS.telescope_builtin_lsp_outgoing_calls,           rhs=builtin.lsp_outgoing_calls},
 {name=NS.telescope_builtin_lsp_document_symbols,         rhs=builtin.lsp_document_symbols},
 {name=NS.telescope_builtin_lsp_workspace_symbols,        rhs=builtin.lsp_workspace_symbols},
 {name=NS.telescope_builtin_lsp_workspace_dynamic_symbols,rhs=builtin.lsp_workspace_dynamic_symbols},
 {name=NS.telescope_builtin_man_pages,                    rhs=builtin.man_pages},
 {name=NS.telescope_builtin_marks,                        rhs=builtin.marks},
 {name=NS.telescope_builtin_oldfiles,                     rhs=builtin.oldfiles},
 {name=NS.telescope_builtin_pickers,                      rhs=builtin.pickers},
 {name=NS.telescope_builtin_planets,                      rhs=builtin.planets},
 {name=NS.telescope_builtin_quickfix,                     rhs=builtin.quickfix},
 {name=NS.telescope_builtin_quickfixhistory,              rhs=builtin.quickfixhistory},
 {name=NS.telescope_builtin_registers,                    rhs=builtin.registers},
 {name=NS.telescope_builtin_reloader,                     rhs=builtin.reloader},
 {name=NS.telescope_builtin_resume,                       rhs=builtin.resume},
 {name=NS.telescope_builtin_search_history,               rhs=builtin.search_history},
 {name=NS.telescope_builtin_spell_suggest,                rhs=builtin.spell_suggest},
 {name=NS.telescope_builtin_symbols,                      rhs=builtin.symbols},
 {name=NS.telescope_builtin_tags,                         rhs=builtin.tags},
 {name=NS.telescope_builtin_tagstack,                     rhs=builtin.tagstack},
 {name=NS.telescope_builtin_treesitter,                   rhs=builtin.treesitter},
 {name=NS.telescope_builtin_vim_options,                  rhs=builtin.vim_options},
 {name=NS.telescope_ast_grep,                             rhs=Wrapper.cmd("Telescope ast_grep")},
 {
  override={priority=2},
  {name=NS.lsp_definition,               rhs=builtin.lsp_definitions},
  {name=NS.lsp_typeDefinition,           rhs=builtin.lsp_type_definitions},
  {name=NS.lsp_implementation,           rhs=builtin.lsp_implementations},
  {name=NS.lsp_references,               rhs=builtin.lsp_references},
  {name=NS.lsp_incoming_calls,           rhs=builtin.lsp_incoming_calls},
  {name=NS.lsp_outgoing_calls,           rhs=builtin.lsp_outgoing_calls},
  {name=NS.lsp_document_symbols,         rhs=builtin.lsp_document_symbols},
  {name=NS.lsp_workspace_symbols,        rhs=builtin.lsp_workspace_symbols},
  {name=NS.lsp_workspace_dynamic_symbols,rhs=builtin.lsp_workspace_dynamic_symbols},
 },
}
